export enum Category{
    DRAWING = 'DRAWING',
    MIXED_MEDIA = 'MIXED_MEDIA',
    PAINTING = 'PAINTING',
    PHOTOGRAPHY = 'PHOTOGRAPHY',
    PRINTS_AND_MULTIPLES = 'PRINTS_AND_MULTIPLES',
    SCULPTURE = 'SCULPTURE',
    STREET_ART = 'STREET_ART',
    POST_WAR_ART = 'POST_WAR_ART',
    PRE_20TH_CENTURY = 'PRE_20TH_CENTURY',
    IMPRESSIONIST_AND_MODERN_ART = 'IMPRESSIONIST_AND_MODERN_ART',
    CONTEMPORARY_ART = 'CONTEMPORARY_ART'
}
   